version: '3'
services:
  app:
    image: hasura-api-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules